{% set name = "jupyter_ascending" %}
{% set version = "0.1.23" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_ascending-{{ version }}.tar.gz
  sha256: 9d759cdb35dbe5ce1db6c06907daa1102b357cd922dcf8d8ca866b91bff60754

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - attrs >=19.0.0
    - edlib >=1.3.8,<2.0.0
    - ipywidgets >=7.5.1,<8.0.0
    - jsonrpcclient >=3.3.5,<4.0.0
    - jsonrpcserver >=4.1.2,<5.0.0
    - jupytext >=1.3.4,<2.0.0
    - loguru >=0.4.1
    - python >={{ python_min }}
    - toml >=0.10.0

test:
  imports:
    - jupyter_ascending
    - jupyter_ascending.handlers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/jupyter-ascending/
  license: MIT
  license_file: LICENSE
  summary: Ascend your Jupyter Notebook usage

extra:
  recipe-maintainers:
    - raybellwaves
