{% set name = "jupyter_ascending" %}
{% set version = "0.1.26" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_ascending-{{ version }}.tar.gz
  sha256: 9cdc6883e1dd51b7c186b5b20e327bdcba74d531c68a11618713e03c44f46970

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - attrs >=19.0.0
    - edlib >=1.3.8,<2.0.0
    - ipywidgets >=7.5.1,<8.0.0
    - jsonrpcclient >=3.3.5,<4.0.0
    - jsonrpcserver >=4.1.2,<5.0.0
    - jupytext >=1.3.4,<2.0.0
    - loguru >=0.4.1
    - python >=3.6
    - toml >=0.10.0

test:
  imports:
    - jupyter_ascending
    - jupyter_ascending.handlers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/jupyter-ascending/
  license: MIT
  license_file: LICENSE
  summary: Ascend your Jupyter Notebook usage

extra:
  recipe-maintainers:
    - raybellwaves
